apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: vault-auth # Service account for Vault access
      containers:
        # Main application container
        - name: app
          image: my-app:latest
          volumeMounts:
            - name: vault-secrets
              mountPath: /etc/secrets
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dummy-secret # Placeholder (not used)

        # Vault Agent Sidecar
        - name: vault-agent
          image: vault:latest
          args: ["agent", "-config=/etc/vault/config.hcl"]
          volumeMounts:
            - name: vault-secrets
              mountPath: /etc/secrets
            - name: vault-config
              mountPath: /etc/vault
      volumes:
        - name: vault-secrets
          emptyDir:
            medium: Memory # Store secrets in memory (not disk)
        - name: vault-config
          configMap:
            name: vault-agent-config
