apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "my-app-role" # Must be pre-configured in Vault
        }
      }
    }

    template {
      destination = "/etc/secrets/db-password"
      contents = <<EOH
      {{- with secret "database/creds/my-app" -}}
      {{ .Data.password }}
      {{- end }}
      EOH
    }
